---
- name: Chris Rohrer                      # Real name of the person
    org: UbuntuNet Alliance                                # Organisation/team they work in
    username: chris                     # username on the lab machine
    github: chrohrer                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Chris Rohrer
        email: chris.rohrer@ubuntunet.net
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim
