---
- name: get some variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
- name: Ensure that EPEL is present and configure
  yum:
    name: "{{ epel_package[ansible_distribution_major_version] }}"
    state: present
  register: epelinstall

- name: Re-generate metadata
  yum:
    name: '*'
    state: latest
  when: epelinstall.changed

- name: Install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: base_packages
