---
 name: Josiah Kisoso                      # Real name of the person
    org: UR                               # Organisation/team they work in
    username: josiah.kisoso                     # username on the lab machine
    github: morendat                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Josiah Kisoso
        email: jskisoso@gmail.com
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim
